=== 4043094/4043094.github.io/xml/network.xsd
<?xml version="1.0"?>
<xs:schema>

    <!-- Reusable simple type for IPv4 addresses -->
    <xs:simpleType name="ipAddressType">
        <xs:restriction base="xs:string">
            <xs:pattern
                value="((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\.){3}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])" />
        </xs:restriction>
    </xs:simpleType>

    <!-- Reusable element declaration -->
    <xs:element name="ip-address" type="ipAddressType" />

    <!-- Reusable login type -->
    <xs:complexType name="loginType">
        <xs:sequence>
            <xs:choice minOccurs="1" maxOccurs="2">
                <xs:element ref="ip-address" />
                <xs:element name="user" type="xs:string" />
            </xs:choice>
            <xs:element name="password" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="routerType">
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="model" type="xs:string" />
            <xs:element name="login" type="loginType" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="deviceType">
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="software" type="xs:string" />
            <xs:element name="runs" type="xs:string" minOccurs="0" />
            <xs:element name="login" type="loginType" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="devicesType">
        <xs:sequence>
            <xs:element name="device" type="deviceType" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:element name="network">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="router" type="routerType" />
                <xs:element name="devices" type="devicesType" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== 4043094/4043094.github.io/xml/network.xml
<?xml version="1.0"?>

<network xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://4043094.github.io/xml"
    xsi:schemaLocation="https://4043094.github.io/xml network.xsd">
    <router>
        <name>Fios by Verizon</name>
        <model>Fios-G1100</model>
        <login>
            <ip-address>192.168.1.1</ip-address>
            <password>tan788work</password>
        </login>
    </router>
    <devices>
        <device>
            <name>raspi</name>
            <software>Raspberry Pi OS</software>
            <login>
                <ip-address>192.168.1.211</ip-address>
                <user>mypi</user>
                <password>ThisIsMyPi</password>
            </login>
        </device>
        <device>
            <name>raspi-2</name>
            <software>Raspberry Pi OS</software>
            <runs>Pi-hole</runs>
            <login>
                <ip-address>192.168.1.3</ip-address>
                <user>mypi</user>
                <password>ThisIsMyPi</password>
            </login>
        </device>
    </devices>
</network>
